### ISSUE TITLE
Typo: git lone --online

### ISSUE THREAD

**Issue by ftnext** [kaityo256/github#11]
わかりやすい講義ノートを公開してくださり、ありがとうございます。
Typoの共有です

https://github.com/kaityo256/github/blob/main/advanced/README.md#%E9%A0%AD%E3%81%8C%E5%8F%96%E3%82%8C%E3%81%9Fdetached-head の1つ目のコードブロックに

`$ git lone --online`

とありますが

`$ git log --oneline`

のtypoと思われます。

https://github.com/kaityo256/github/search?q=online と検索したところ、この1箇所を直した後、advanced/index.html を更新する必要がありそうです

**Comment by kaityo256** [comment]
@ftnext ご指摘ありがとうございます。

Markdown, HTMLともにタイポを修正しておきました🙇
